/* FONTS */
import { primary_font, secondary_font } from "@/lib/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "OneXReferral - One referral can change everything",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${primary_font} ${secondary_font}`}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
