import { poppins, source_sans } from "@/utils/fonts";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: "OneXReferral",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased ${poppins} ${source_sans}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
