import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/screens/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        greyBg: "#F5F5F5",
        greyBorder: "#E5E5E5",
        greyText: "#777",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      fontFamily: {
        primary: ["var(--font-primary)", "sans-serif"],
        secondary: ["var(--font-secondary)", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        "0": "0vh",
        "1": "0.5vh",
        "2": "1.0vh",
        "3": "1.5vh",
        "4": "2.0vh",
        "5": "2.5vh",
        "6": "3.0vh",
        "7": "3.5vh",
        "8": "4.0vh",
        "9": "4.5vh",
        "10": "5.0vh",
        "11": "5.5vh",
        "12": "6.0vh",
        "14": "7.0vh",
        "16": "8.0vh",
        "20": "10.0vh",
        "24": "12.0vh",
        "28": "14.0vh",
        "32": "16.0vh",
        "36": "18.0vh",
        "40": "20.0vh",
        "44": "22.0vh",
        "48": "24.0vh",
        "52": "26.0vh",
        "56": "28.0vh",
        "60": "30.0vh",
        "64": "32.0vh",
        "72": "36.0vh",
        "80": "40.0vh",
        "96": "48.0vh",
        "0.5": "0.3vh",
        "1.5": "0.8vh",
        "2.5": "1.3vh",
        "3.5": "1.8vh",
      },
      fontSize: {
        "9xl": "16.0vh",
        "8xl": "12.0vh",
        "7xl": "9.0vh",
        "6xl": "7.5vh",
        "5xl": "6.0vh",
        "4xl": "4.5vh",
        "3xl": "3.8vh",
        "2xl": "3.0vh",
        xl: "2.5vh",
        lg: "2.3vh",
        base: "2.0vh",
        sm: "1.8vh",
        xs: "1.5vh",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
