import SignInScreen from "@/screens/auth/sign-in";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Sign In | OneXReferral - One referral can change everything",
  description: "Generated by create next app",
};

const SignInPage = () => {
  return <SignInScreen />;
};

export default SignInPage;
