import { poppins, source_sans } from "@/utils/fonts";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/layout/header";

export const metadata = {
  title: "OneXReferral - One Referral Can Change Everything",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins} ${source_sans}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="h-screen">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
