import type { Metadata } from "next";

/*STYLES*/
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "OneXReferral - One referral can change everything",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
