import type { Metadata } from "next";

/*STYLES*/
import "@/styles/globals.css";

/* FONTS */
import { primary_font, secondary_font } from "@/lib/fonts";

/*COMPONENTS*/
import { ThemeProvider } from "@/components/theme-provider";
import { Bounce, ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "OneXReferral - One referral can change everything",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${primary_font} ${secondary_font}`}
      suppressHydrationWarning
    >
      <body className={`antialiased`}>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
