import type { Metadata } from "next";
import "@/styles/globals.css";

/* FONTS */
import { primary_font, secondary_font } from "@/lib/fonts";
import Header from "@/components/layout/header";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "OneXReferral - One referral can change everything",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${primary_font} ${secondary_font}`}
      suppressHydrationWarning
    >
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
