import type { Metadata } from "next";

/*COMPONENTS*/
import Header from "@/components/layout/header";

export const metadata: Metadata = {
  title: "OneXReferral - One referral can change everything",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
