import JoinAsScreen from "@/screens/auth/join-as";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Join As | OneXReferral - One referral can change everything",
  description: "Generated by create next app",
};

const JoinAsPage = () => {
  return <JoinAsScreen />;
};

export default JoinAsPage;
